// Extracted verbatim from figma-shader-orb/index.html — the per-shader metadata
// (names, control schema tuples, layout, deps, presets, defaults).
export const EFFECTS = {
  orb: {
    name: 'orb',
    assets: ['asset-orbbg'],
    fileAssets: { imageUpload: 'asset-orbbg' },
    deps: {
      nodeColor: c => c.showNodes,
      nodeMin: c => c.showNodes,
      nodeMax: c => c.showNodes,
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
      imageOpacity: c => c.imageOn,
    },
    hint: 'sweep your cursor through the spikes — they steer away',
    openGroups: ['Structure', 'Gradient rings', 'Spikes'],
    LAYOUT: [
      { t: 'background', toggle: 'imageOn', groups: ['Background media'] },
      { t: 'orb', groups: ['Structure', 'Gradient rings', 'Spikes', 'End nodes'],
        rename: { 'Structure': 'structure', 'Gradient rings': 'gradient rings', 'Spikes': 'spikes', 'End nodes': 'end nodes' } },
      { t: 'motion', groups: ['Idle motion'] },
      { t: 'cursor', groups: ['Cursor physics'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'ring4',
    DEFAULTS: {
      count: 250, seed: 0, circleRadius: 0.90,
      imageOn: true, imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false, imageOpacity: 1,
      ring1: '#f9b85f', ring2: '#d9ccb0', ring3: '#b6d9ff', ring4: '#ffffff',
      ringEnd1: 0.25, ringEnd2: 0.35, ringEnd3: 0.58, blendSoft: 0.14,
      spikeColor: '#2a00ff', lenMin: 0.16, lenMax: 0.42,
      innerMin: 0.015, innerMax: 0.065,
      tipWidthMin: 0.1, tipWidthMax: 0.5, taper: 0.10,
      centerFade: 0.10, fadeReach: 0.60,
      showNodes: true, nodeColor: '#2a00ff', nodeMin: 0.7, nodeMax: 2.6,
      timeScale: 1.0, tumbleX: 0.07, tumbleY: 0.10, wobbleAmp: 0.025, wobbleSpeed: 0.5,
      cursorPull: -0.85, cursorRadius: 0.30, squish: 0.35,
      stiffness: 90, damping: 14,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Background media', [
        ['background color', 'ring4', 'color'],
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['media opacity', 'imageOpacity', 0, 1, 0.01],
      ]],
      ['Structure', [
        ['particle count', 'count', 10, 800, 1, 'rebuild'],
        ['seed', 'seed', 0, 999, 1, 'rebuild'],
        ['circle radius', 'circleRadius', 0.3, 1.0, 0.01],
      ]],
      ['Gradient rings', [
        ['ring 1 color (center)', 'ring1', 'color'],
        ['ring 2 color', 'ring2', 'color'],
        ['ring 3 color', 'ring3', 'color'],
        ['ring 1 ends at', 'ringEnd1', 0.02, 0.9, 0.01],
        ['ring 2 ends at', 'ringEnd2', 0.05, 0.95, 0.01],
        ['ring 3 ends at', 'ringEnd3', 0.1, 1.0, 0.01],
        ['blend softness', 'blendSoft', 0.005, 0.5, 0.005],
      ]],
      ['Spikes', [
        ['color', 'spikeColor', 'color'],
        ['length · min', 'lenMin', 0.02, 0.9, 0.005, 'rebuild'],
        ['length · max', 'lenMax', 0.05, 0.9, 0.005, 'rebuild'],
        ['start gap · min', 'innerMin', 0, 0.3, 0.005, 'rebuild'],
        ['start gap · max', 'innerMax', 0, 0.3, 0.005, 'rebuild'],
        ['tip width · min', 'tipWidthMin', 0.05, 4, 0.05],
        ['tip width · max', 'tipWidthMax', 0.05, 6, 0.05],
        ['taper', 'taper', 0, 1, 0.01],
        ['center fade', 'centerFade', 0, 1, 0.01],
        ['fade reach', 'fadeReach', 0.05, 1, 0.01],
      ]],
      ['End nodes', [
        ['visible', 'showNodes', 'check'],
        ['color', 'nodeColor', 'color'],
        ['size · min', 'nodeMin', 0, 8, 0.1],
        ['size · max', 'nodeMax', 0, 12, 0.1],
      ]],
      ['Idle motion', [
        ['speed (global)', 'timeScale', 0, 4, 0.05],
        ['tumble · x axis', 'tumbleX', 0, 0.6, 0.005],
        ['tumble · y axis', 'tumbleY', 0, 0.6, 0.005],
        ['wobble amount', 'wobbleAmp', 0, 0.2, 0.001],
        ['wobble speed', 'wobbleSpeed', 0, 4, 0.05],
      ]],
      ['Cursor physics', [
        ['pull (− repels)', 'cursorPull', -3, 3, 0.05],
        ['pull radius', 'cursorRadius', 0.05, 1.5, 0.01],
        ['radial squish', 'squish', -0.5, 0.9, 0.01],
        ['spring stiffness', 'stiffness', 5, 300, 1],
        ['spring damping', 'damping', 0.5, 30, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },

  lava: {
    name: 'lava',
    assets: ['asset-lavabg'],
    fileAssets: { imageUpload: 'asset-lavabg' },
    deps: {
      color5: c => c.bandCount >= 5,
      color6: c => c.bandCount >= 6,
      color7: c => c.bandCount >= 7,
      color8: c => c.bandCount >= 8,
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
      imageOpacity: c => c.imageOn,
    },
    hint: 'move your cursor into the lava — it tears apart',
    openGroups: ['Blobs', 'Color steps'],
    LAYOUT: [
      { t: 'background', toggle: 'imageOn', groups: ['Background media'] },
      { t: 'lava', groups: ['Blobs', 'Color steps', 'Motion', 'Cursor physics'],
        rename: { 'Blobs': 'blobs', 'Color steps': 'color steps', 'Motion': 'motion', 'Cursor physics': 'cursor' } },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg',
    DEFAULTS: {
      blobCount: 6, seed: 0, blobSize: 0.30,
      imageOn: true, imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false, imageOpacity: 1,
      bg: '#ffffff', bg2: '#dbe4ff',
      bandCount: 4,
      color1: '#b6d9ff', color2: '#d9ccb0', color3: '#f9b85f', color4: '#ff6b35',
      color5: '#ff2e63', color6: '#b38dff', color7: '#2a00ff', color8: '#1a0533',
      steps: 5, softness: 0.07, coreSize: 1.6, coreStart: 0.58,
      tightness: 1.8, glow: 0.4, ringOpacity: 0.5, opacityStep: 0.07,
      speed: 0.35, rise: 0.6, warpAmount: 0.10, warpScale: 3.5,
      cursorPull: -1.2, cursorRadius: 0.55, shatter: 0.9, stiffness: 15, damping: 9,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Background media', [
        ['background top', 'bg', 'color'],
        ['background bottom', 'bg2', 'color'],
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['media opacity', 'imageOpacity', 0, 1, 0.01],
      ]],
      ['Blobs', [
        ['blob count', 'blobCount', 2, 16, 1, 'rebuild'],
        ['seed', 'seed', 0, 999, 1, 'rebuild'],
        ['blob size', 'blobSize', 0.05, 0.8, 0.005],
      ]],
      ['Color steps', [
        ['band count', 'bandCount', 2, 8, 1],
        ['band 1 (outer)', 'color1', 'color'],
        ['band 2', 'color2', 'color'],
        ['band 3', 'color3', 'color'],
        ['band 4', 'color4', 'color'],
        ['band 5', 'color5', 'color'],
        ['band 6', 'color6', 'color'],
        ['band 7', 'color7', 'color'],
        ['band 8', 'color8', 'color'],
        ['gradient steps', 'steps', 2, 12, 1],
        ['band softness', 'softness', 0.01, 1, 0.01],
        ['band tightness', 'tightness', 0.5, 4, 0.05],
        ['edge glow', 'glow', 0, 1, 0.01],
        ['ring opacity (outer)', 'ringOpacity', 0, 1, 0.01],
        ['opacity step / ring', 'opacityStep', -0.2, 0.2, 0.005],
        ['core size', 'coreSize', 0.3, 3, 0.05],
        ['core starts at', 'coreStart', 0.5, 0.92, 0.01],
      ]],
      ['Motion', [
        ['speed', 'speed', 0, 2, 0.01],
        ['rise / fall', 'rise', 0, 1.5, 0.01],
        ['goo amount', 'warpAmount', 0, 0.5, 0.005],
        ['goo scale', 'warpScale', 0.5, 12, 0.1],
      ]],
      ['Cursor physics', [
        ['pull (\u2212 repels)', 'cursorPull', -3, 3, 0.05],
        ['pull radius', 'cursorRadius', 0.05, 1.5, 0.01],
        ['shatter', 'shatter', 0, 2, 0.02],
        ['spring stiffness', 'stiffness', 5, 300, 1],
        ['spring damping', 'damping', 0.5, 30, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },

  pixels: {
    name: 'pixels',
    deps: {
      bg: c => !c.imageOn,
      pixelScale: c => c.imageOn, sizeMix: c => c.imageOn,
      maxPixel: c => c.imageOn, minPixel: c => c.imageOn,
      spotRadius: c => c.imageOn, coreSize: c => c.imageOn, spotPixel: c => c.imageOn,
      edgeBlur: c => c.imageOn, edgeSoftness: c => c.imageOn, rimJitter: c => c.imageOn,
      blinkSpeed: c => c.imageOn,
      blinkDensity: c => c.imageOn && c.blinkSpeed > 0,
      blinkBand: c => c.imageOn && c.blinkSpeed > 0,
      wanderSpeed: c => c.wander,
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
    },
    hint: 'the spotlight follows your cursor · upload your own image',
    openGroups: ['Image / video', 'Mosaic', 'Spotlight'],
    LAYOUT: [
      { t: 'image', toggle: 'imageOn', groups: ['Image / video', 'Mosaic', 'Spotlight'],
        rename: { 'Image / video': 'source', 'Mosaic': 'mosaic', 'Spotlight': 'spotlight' } },
      { t: 'motion', groups: ['Motion'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg',
    assets: ['asset-pixelbg'],
    fileAssets: { imageUpload: 'asset-pixelbg' },
    DEFAULTS: {
      imageOn: true, imageFocus: 0.1, bg: '#ffffff',
      imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false,
      pixelScale: 128, sizeMix: 0.55, maxPixel: 4, minPixel: 1,
      spotRadius: 0.38, coreSize: 0.35, edgeBlur: 3, edgeSoftness: 0.3,
      blinkSpeed: 8, blinkDensity: 0.35, blinkBand: 0.22,
      spotPixel: 2, rimJitter: 0.35,
      followEase: 9, wander: true, wanderSpeed: 0.5,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Image / video', [
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['background', 'bg', 'color'],
      ]],
      ['Mosaic', [
        ['pixel scale', 'pixelScale', 32, 256, 8],
        ['size mix', 'sizeMix', 0, 1, 0.01],
        ['max pixel size', 'maxPixel', 1, 8, 1],
        ['min pixel size', 'minPixel', 1, 8, 1],
      ]],
      ['Spotlight', [
        ['radius', 'spotRadius', 0.08, 0.9, 0.01],
        ['clear core size', 'coreSize', 0.05, 0.95, 0.01],
        ['spot pixel size', 'spotPixel', 1, 8, 1],
        ['edge blur', 'edgeBlur', 0, 6, 0.1],
        ['edge softness', 'edgeSoftness', 0.02, 0.9, 0.01],
        ['rim break-up', 'rimJitter', 0, 0.8, 0.01],
        ['blink speed', 'blinkSpeed', 0, 30, 0.5],
        ['blink density', 'blinkDensity', 0, 1, 0.01],
        ['blink band', 'blinkBand', 0.02, 0.6, 0.01],
      ]],
      ['Motion', [
        ['follow ease', 'followEase', 1, 30, 0.5],
        ['idle wander', 'wander', 'check'],
        ['wander speed', 'wanderSpeed', 0.05, 2, 0.05],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },

  particle: {
    name: 'particle',
    assets: ['asset-particlebg'],
    fileAssets: { imageUpload: 'asset-particlebg' },
    deps: {
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
      imageOpacity: c => c.imageOn,
      wobbleSpeed: c => c.wobbleAmp > 0,
      twinkleSpeed: c => c.twinkle > 0,
    },
    hint: 'drift your cursor through the field — particles scatter, then settle',
    openGroups: ['Background', 'Particles', 'Depth'],
    LAYOUT: [
      { t: 'background', groups: ['Background'] },
      { t: 'particles', groups: ['Particles', 'Depth'],
        rename: { 'Particles': 'appearance', 'Depth': 'depth' } },
      { t: 'motion', groups: ['Motion'] },
      { t: 'cursor', groups: ['Cursor physics'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg',
    DEFAULTS: {
      count: 160, seed: 0,
      bg: '#ffffff', bg2: '#e9edf2',
      imageOn: true, imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false, imageOpacity: 1,
      color: '#111111', size: 4.5, sizeVar: 0.7, opacity: 0.85, softness: 0.25,
      irregular: 0.65, grain: 0.4, stretch: 0.45,
      depth: 0.8, perspective: 2.6, depthFade: 0.55, depthShrink: 0.45,
      driftSpeed: 0.5, rise: 0.18, wind: 0.04, wobbleAmp: 0.05, wobbleSpeed: 0.7,
      twinkle: 0.3, twinkleSpeed: 0.8,
      cursorPull: -0.8, cursorRadius: 0.35, stiffness: 60, damping: 7,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Background', [
        ['top color', 'bg', 'color'],
        ['bottom color', 'bg2', 'color'],
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['media opacity', 'imageOpacity', 0, 1, 0.01],
      ]],
      ['Particles', [
        ['particle count', 'count', 1, 600, 1, 'rebuild'],
        ['seed', 'seed', 0, 999, 1, 'rebuild'],
        ['color', 'color', 'color'],
        ['size', 'size', 0.5, 24, 0.1],
        ['size variation', 'sizeVar', 0, 1, 0.01],
        ['irregularity', 'irregular', 0, 1, 0.01],
        ['grain', 'grain', 0, 1, 0.01],
        ['stretch', 'stretch', 0, 1, 0.01],
        ['opacity', 'opacity', 0, 1, 0.01],
        ['edge softness', 'softness', 0, 1, 0.01],
      ]],
      ['Depth', [
        ['depth range', 'depth', 0, 0.95, 0.01],
        ['perspective', 'perspective', 1.2, 5, 0.05],
        ['depth fade', 'depthFade', 0, 0.95, 0.01],
        ['depth shrink', 'depthShrink', 0, 0.95, 0.01],
      ]],
      ['Motion', [
        ['drift speed', 'driftSpeed', 0, 3, 0.01],
        ['rise (− falls)', 'rise', -1, 1, 0.01],
        ['wind (− blows left)', 'wind', -1, 1, 0.01],
        ['wobble amount', 'wobbleAmp', 0, 0.3, 0.002],
        ['wobble speed', 'wobbleSpeed', 0, 4, 0.05],
        ['twinkle', 'twinkle', 0, 1, 0.01],
        ['twinkle speed', 'twinkleSpeed', 0, 4, 0.05],
      ]],
      ['Cursor physics', [
        ['pull (− repels)', 'cursorPull', -3, 3, 0.05],
        ['pull radius', 'cursorRadius', 0.05, 1.5, 0.01],
        ['spring stiffness', 'stiffness', 5, 300, 1],
        ['spring damping', 'damping', 0.5, 30, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },

  tide: {
    name: 'tide',
    assets: ['asset-tidebg'],
    fileAssets: { imageUpload: 'asset-tidebg' },
    deps: {
      count: c => c.blobsOn,
      seed: c => c.blobsOn,
      size: c => c.blobsOn,
      sizeVariation: c => c.blobsOn,
      edgeSoftness: c => c.blobsOn,
      opacity: c => c.blobsOn,
      palettePreset: c => c.blobsOn,
      paletteCount: c => c.blobsOn,
      blobColor1: c => c.blobsOn,
      blobColor2: c => c.blobsOn && c.paletteCount >= 2,
      blobColor3: c => c.blobsOn && c.paletteCount >= 3,
      blobColor4: c => c.blobsOn && c.paletteCount >= 4,
      blobColor5: c => c.blobsOn && c.paletteCount >= 5,
      blobColor6: c => c.blobsOn && c.paletteCount >= 6,
      blobColor7: c => c.blobsOn && c.paletteCount >= 7,
      blobColor8: c => c.blobsOn && c.paletteCount >= 8,
      blobColor9: c => c.blobsOn && c.paletteCount >= 9,
      blobColor10: c => c.blobsOn && c.paletteCount >= 10,
      fillLevel: c => c.blobsOn,
      boundarySoft: c => c.blobsOn,
      surfaceLine: c => c.blobsOn,
      surfaceColor: c => c.blobsOn && c.surfaceLine > 0,
      rgbSplit: c => c.blobsOn,
      blobShape: c => c.blobsOn,
      blobSquish: c => c.blobsOn,
      blobStatic: c => c.blobsOn,
      speed: c => c.blobsOn && !c.blobStatic,
      colorDrift: c => c.blobsOn && !c.blobStatic,
      driftSpeed: c => c.blobsOn && !c.blobStatic,
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
      imageOpacity: c => c.imageOn,
    },
    hint: 'stir the pool — blobs lean toward your cursor · the boundary panel sets the waterline',
    openGroups: ['Blobs', 'Blob colors', 'Boundary'],
    LAYOUT: [
      { t: 'blobs', toggle: 'blobsOn', groups: ['Blobs', 'Blob colors', 'Motion'],
        rename: { 'Blobs': 'shape', 'Blob colors': 'colors', 'Motion': 'motion' } },
      { t: 'boundary', groups: ['Boundary'] },
      { t: 'background', groups: ['Background media', 'Background'],
        rename: { 'Background media': 'media', 'Background': 'colors' } },
      { t: 'cursor', groups: ['Cursor physics'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg1',
    // palette presets: one seg click restyles background + all blob colors
    presets: {
      key: 'palettePreset',
      options: [
        { bg1: '#ffffff', bg2: '#ffe9d6', blobColor1: '#f9b85f', blobColor2: '#ffd9ec', blobColor3: '#b6d9ff',
          blobColor4: '#ffb37a', blobColor5: '#ffe3a3', blobColor6: '#ff6b35', paletteCount: 5 },   // dawn
        { bg1: '#232438', bg2: '#3b2f54', blobColor1: '#7a5cff', blobColor2: '#ff6b9d', blobColor3: '#4dc9ff',
          blobColor4: '#2a2f6e', blobColor5: '#ff9d5c', blobColor6: '#8e7cff', paletteCount: 5 },   // dusk
        { bg1: '#f4f7f0', bg2: '#dce8d4', blobColor1: '#7fae6e', blobColor2: '#c9f0d8', blobColor3: '#eef7b8',
          blobColor4: '#4d7c4a', blobColor5: '#a3d9a5', blobColor6: '#2f5d2b', paletteCount: 5 },   // moss
        { bg1: '#ffffff', bg2: '#e8e8e8', blobColor1: '#111111', blobColor2: '#555555', blobColor3: '#999999',
          blobColor4: '#cccccc', blobColor5: '#333333', blobColor6: '#777777', paletteCount: 5 },   // mono
      ],
    },
    DEFAULTS: {
      blobsOn: true,
      count: 7, seed: 0, size: 0.34, sizeVariation: 0.45, blobShape: 0, blobSquish: 0.65,
      edgeSoftness: 1.2, opacity: 0.9, saturation: 1,
      palettePreset: 0, paletteCount: 5,
      blobColor1: '#f9b85f', blobColor2: '#ffd9ec', blobColor3: '#b6d9ff',
      blobColor4: '#ffb37a', blobColor5: '#ffe3a3', blobColor6: '#ff6b35',
      blobColor7: '#d9ccb0', blobColor8: '#c9b8ff', blobColor9: '#c9f0d8', blobColor10: '#ff8fb3',
      colorDrift: 0.05, driftSpeed: 0.25, rgbSplit: 0,
      fillLevel: 0.45, boundarySoft: 0.08, surfaceLine: 0, surfaceColor: '#111111',
      bg1: '#ffffff', bg2: '#ffe9d6', gradientAngle: 270, edgeBlur: 0,
      speed: 0.2, blobStatic: false,
      imageOn: true, imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false, imageOpacity: 1,
      cursorPull: 0.8, cursorRadius: 0.5, stiffness: 60, damping: 6,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Blobs', [
        ['blob count', 'count', 2, 12, 1, 'rebuild'],
        ['seed', 'seed', 0, 999, 1, 'rebuild'],
        ['size', 'size', 0.05, 0.9, 0.005],
        ['size variation', 'sizeVariation', 0, 0.9, 0.01],
        ['shape irregularity', 'blobShape', 0, 1, 0.01],
        ['collision squish', 'blobSquish', 0, 1, 0.01],
        ['edge softness', 'edgeSoftness', 0.2, 3, 0.05],
        ['opacity', 'opacity', 0.1, 1, 0.01],
      ]],
      ['Blob colors', [
        ['preset', 'palettePreset', 'seg', ['dawn', 'dusk', 'moss', 'mono']],
        ['palette count', 'paletteCount', 1, 10, 1],
        ['color 1', 'blobColor1', 'color'],
        ['color 2', 'blobColor2', 'color'],
        ['color 3', 'blobColor3', 'color'],
        ['color 4', 'blobColor4', 'color'],
        ['color 5', 'blobColor5', 'color'],
        ['color 6', 'blobColor6', 'color'],
        ['color 7', 'blobColor7', 'color'],
        ['color 8', 'blobColor8', 'color'],
        ['color 9', 'blobColor9', 'color'],
        ['color 10', 'blobColor10', 'color'],
        ['color drift', 'colorDrift', 0, 0.2, 0.005],
        ['drift speed', 'driftSpeed', 0, 2, 0.01],
        ['rgb edge split', 'rgbSplit', 0, 0.5, 0.005],
      ]],
      ['Boundary', [
        ['fill level', 'fillLevel', 0, 1, 0.005],
        ['edge softness', 'boundarySoft', 0.005, 0.5, 0.005],
        ['surface line', 'surfaceLine', 0, 1, 0.01],
        ['line color', 'surfaceColor', 'color'],
      ]],
      ['Motion', [
        ['static (freeze blobs)', 'blobStatic', 'check'],
        ['speed', 'speed', 0, 1, 0.005],
      ]],
      ['Background media', [
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['media opacity', 'imageOpacity', 0, 1, 0.01],
      ]],
      ['Background', [
        ['color 1', 'bg1', 'color'],
        ['color 2', 'bg2', 'color'],
        ['gradient angle', 'gradientAngle', 0, 360, 1],
        ['saturation', 'saturation', 0, 2, 0.01],
        ['frame edge blur', 'edgeBlur', 0, 0.8, 0.005],
      ]],
      ['Cursor physics', [
        ['pull (− repels)', 'cursorPull', -3, 3, 0.05],
        ['pull radius', 'cursorRadius', 0.05, 1.5, 0.01],
        ['spring stiffness', 'stiffness', 5, 300, 1],
        ['spring damping', 'damping', 0.5, 30, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },

  silk: {
    name: 'silk',
    deps: {
      color2: c => c.anchorCount >= 2,
      color3: c => c.anchorCount >= 3,
      color4: c => c.anchorCount >= 4,
      color5: c => c.anchorCount >= 5,
      color6: c => c.anchorCount >= 6,
      streakAngle: c => c.streakCount > 0,
      streakWidth: c => c.streakCount > 0,
      streakLen: c => c.streakCount > 0,
      streakIntensity: c => c.streakCount > 0,
      streakTint: c => c.streakCount > 0,
      shimmer: c => c.streakCount > 0,
      driftSpeed: c => !c.silkStatic,
      surfaceColor: c => c.surfaceLine > 0,
    },
    hint: 'anchors lean toward your cursor · streaks shimmer on their own',
    openGroups: ['Gradient', 'Colors', 'Streaks'],
    LAYOUT: [
      { t: 'gradient', groups: ['Gradient', 'Colors'],
        rename: { 'Gradient': 'field', 'Colors': 'colors' } },
      { t: 'streaks', groups: ['Streaks'] },
      { t: 'boundary', groups: ['Boundary'] },
      { t: 'motion', groups: ['Motion'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'baseColor',
    // palettes: dawnlight mirrors the reference photograph
    presets: {
      key: 'palettePreset',
      options: [
        { baseColor: '#f6e7da', color1: '#1747e0', color2: '#0f93ab', color3: '#ff8a00',
          color4: '#ffc93c', color5: '#ffb6c8', color6: '#ff2fd2' },               // dawnlight
        { baseColor: '#eef4fa', color1: '#0f2f8f', color2: '#2fa8c9', color3: '#8fd0e8',
          color4: '#c9e6f4', color5: '#e3d3ff', color6: '#4a3d8f' },               // arctic
        { baseColor: '#1a0e14', color1: '#3d1030', color2: '#7a1f3d', color3: '#ff5a2a',
          color4: '#ffb347', color5: '#ff2f6e', color6: '#5c1b8f' },               // ember
        { baseColor: '#f2f7e8', color1: '#2f7fa8', color2: '#7fae6e', color3: '#eef7b8',
          color4: '#ffd9a0', color5: '#c9f0d8', color6: '#4d7c4a' },               // meadow
      ],
    },
    DEFAULTS: {
      anchorCount: 6, seed: 0, spread: 1, softness: 1.4,
      warp: 0.35, warpScale: 1.6, grain: 0.12,
      palettePreset: 0,
      baseColor: '#f6e7da',
      color1: '#1747e0', color2: '#0f93ab', color3: '#ff8a00',
      color4: '#ffc93c', color5: '#ffb6c8', color6: '#ff2fd2',
      streakCount: 3, streakAngle: 58, streakWidth: 0.16, streakLen: 1.2,
      streakIntensity: 0.55, streakTint: '#fff3d8', shimmer: 0.4,
      fillLevel: 1, boundarySoft: 0.08, surfaceLine: 0, surfaceColor: '#111111',
      driftSpeed: 0.3, silkStatic: false,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Gradient', [
        ['anchor count', 'anchorCount', 3, 6, 1],
        ['seed', 'seed', 0, 999, 1],
        ['color spread', 'spread', 0.5, 2, 0.01],
        ['softness', 'softness', 0.3, 3, 0.05],
        ['cloud warp', 'warp', 0, 0.8, 0.01],
        ['warp scale', 'warpScale', 0.5, 6, 0.1],
        ['grain', 'grain', 0, 1, 0.01],
      ]],
      ['Colors', [
        ['background color', 'baseColor', 'color'],
        ['preset', 'palettePreset', 'seg', ['dawnlight', 'arctic', 'ember', 'meadow']],
        ['color 1', 'color1', 'color'],
        ['color 2', 'color2', 'color'],
        ['color 3', 'color3', 'color'],
        ['color 4', 'color4', 'color'],
        ['color 5', 'color5', 'color'],
        ['color 6', 'color6', 'color'],
      ]],
      ['Streaks', [
        ['streaks', 'streakCount', 0, 6, 1],
        ['angle', 'streakAngle', 0, 180, 1],
        ['width', 'streakWidth', 0.03, 0.5, 0.005],
        ['length', 'streakLen', 0.2, 2.5, 0.05],
        ['intensity', 'streakIntensity', 0, 1, 0.01],
        ['tint', 'streakTint', 'color'],
        ['shimmer', 'shimmer', 0, 2, 0.01],
      ]],
      ['Boundary', [
        ['fill level', 'fillLevel', 0, 1, 0.005],
        ['edge softness', 'boundarySoft', 0.005, 0.5, 0.005],
        ['surface line', 'surfaceLine', 0, 1, 0.01],
        ['line color', 'surfaceColor', 'color'],
      ]],
      ['Motion', [
        ['drift speed', 'driftSpeed', 0, 2, 0.01],
        ['static (freeze)', 'silkStatic', 'check'],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },
  bleed: {
    name: 'bleed',
    assets: ['asset-bleedbg'],
    fileAssets: { imageUpload: 'asset-bleedbg' },
    deps: {
      c3: c => c.stopCount >= 3,
      c4: c => c.stopCount >= 4,
      c5: c => c.stopCount >= 5,
      c6: c => c.stopCount >= 6,
      c7: c => c.stopCount >= 7,
      c8: c => c.stopCount >= 8,
      riseTime: c => c.riseOn,
      breathe: c => c.speed > 0,
      shimmer: c => c.speed > 0,
      foldDepth: c => c.fold > 0,
      imageUpload: c => c.imageOn,
      imageRotate: c => c.imageOn,
      imageZoom: c => c.imageOn,
      imageFlip: c => c.imageOn,
      imageOpacity: c => c.imageOn,
    },
    // two preset rows: shape experiments and colour palettes from the
    // original dia-gradient case study (arlan.me/vault/dia-gradient)
    presets: [
      { key: 'palettePreset', options: [
        { stopCount: 8, c1: '#340b05', c2: '#0358f7', c3: '#5092c7', c4: '#e1ecfe',
          c5: '#ffd400', c6: '#fa3d1d', c7: '#fd02f5', c8: '#ffc0fd' },                 // dia
        { stopCount: 6, c1: '#ff7ab6', c2: '#ffa1d2', c3: '#c9a8ff',
          c4: '#a7d8ff', c5: '#fff3b0', c6: '#ffffff' },                                // candy
        { stopCount: 6, c1: '#021018', c2: '#0b6e4f', c3: '#1fd18e',
          c4: '#9cf6c8', c5: '#56d6e8', c6: '#cffaf2' },                                // aurora
      ] },
      { key: 'shapePreset', options: [
        { bars: 9, spread: 1.35, jitter: 0.12, peak: 0.92, valley: 0.5, curve: 1.24,
          melt: 0.6, feather: 0.5, halo: 0.1, fold: 0, blendMode: 0, brightness: 1,
          bg: '#ffffff' },                                                              // classic
        { bars: 16, spread: 1.6, jitter: 0, peak: 0.92, valley: 0.06, curve: 0.7,
          melt: 1.5, feather: 0.6, halo: 0.12, fold: 0, blendMode: 0, brightness: 1 },  // peaked
        { bars: 9, spread: 1.35, jitter: 0.12, peak: 0.92, valley: 0.5, curve: 1.24,
          melt: 0.6, feather: 0.5, halo: 0.1, fold: 74, foldDepth: 1.05,
          blendMode: 0, brightness: 1 },                                                // 3d fold
        { bars: 9, spread: 1.35, jitter: 0.12, peak: 0.92, valley: 0.5, curve: 1.24,
          melt: 0.6, feather: 0.5, halo: 0.1, fold: 0, blendMode: 2,
          brightness: 0.8, bg: '#6a6a72' },                                             // dodge
      ] },
    ],
    hint: 'sweep across the floor — the colour field reaches up toward your cursor',
    openGroups: ['Bars', 'Colors', 'Shape'],
    LAYOUT: [
      { t: 'background', toggle: 'imageOn', groups: ['Background media'] },
      { t: 'bleed', groups: ['Bars', 'Shape', 'Colors', 'Blur'],
        rename: { 'Bars': 'bars', 'Shape': 'shape', 'Colors': 'colors', 'Blur': 'blur' } },
      { t: 'motion', groups: ['Motion'] },
      { t: 'cursor', groups: ['Cursor physics'] },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg',
    DEFAULTS: {
      bars: 9, seed: 0, spread: 1.35, jitter: 0.12,
      peak: 0.92, valley: 0.5, curve: 1.24,
      shapePreset: 0, fold: 0, foldDepth: 1.05,
      bg: '#ffffff', brightness: 1.0, blendMode: 0,
      palettePreset: 0, stopCount: 8,
      c1: '#340b05', c2: '#0358f7', c3: '#5092c7', c4: '#e1ecfe',
      c5: '#ffd400', c6: '#fa3d1d', c7: '#fd02f5', c8: '#ffc0fd',
      melt: 0.6, feather: 0.5, halo: 0.1, colorSoft: 0.6,
      speed: 0.5, breathe: 0.1, shimmer: 0.12,
      riseOn: true, riseTime: 1.1,
      cursorLift: 0.18, cursorGlow: 0.9, cursorRadius: 0.18, stiffness: 60, damping: 8,
      imageOn: false, imageRotate: 0, imageZoom: 1, imageX: 0, imageY: 0, imageFlip: false, imageOpacity: 1,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Background media', [
        ['upload image / video', 'imageUpload', 'file'],
        ['show media', 'imageOn', 'check'],
        ['rotate media', 'imageRotate', 'rot'],
        ['crop media', 'imageZoom', 'crop'],
        ['flip horizontal', 'imageFlip', 'check'],
        ['media opacity', 'imageOpacity', 0, 1, 0.01],
      ]],
      ['Bars', [
        ['bar count', 'bars', 2, 24, 1],
        ['seed', 'seed', 0, 999, 1],
        ['bar spread', 'spread', 0.8, 2.5, 0.01],
        ['height jitter', 'jitter', 0, 0.6, 0.01],
      ]],
      ['Shape', [
        ['preset', 'shapePreset', 'seg', ['classic', 'peaked', '3d fold', 'dodge']],
        ['peak height', 'peak', 0.3, 1, 0.01],
        ['edge height', 'valley', 0, 1, 0.01],
        ['curve', 'curve', 0.4, 4, 0.02],
        ['fold angle', 'fold', 0, 85, 1],
        ['fold depth', 'foldDepth', 0.3, 3, 0.05],
      ]],
      ['Colors', [
        ['palette', 'palettePreset', 'seg', ['dia', 'candy', 'aurora']],
        ['stage / backdrop', 'bg', 'color'],
        ['blend', 'blendMode', 'seg', ['paint', 'glow', 'dodge']],
        ['brightness', 'brightness', 0, 3, 0.02],
        ['color count', 'stopCount', 2, 8, 1],
        ['stop 1 (floor)', 'c1', 'color'],
        ['stop 2', 'c2', 'color'],
        ['stop 3', 'c3', 'color'],
        ['stop 4', 'c4', 'color'],
        ['stop 5', 'c5', 'color'],
        ['stop 6', 'c6', 'color'],
        ['stop 7', 'c7', 'color'],
        ['stop 8 (crest)', 'c8', 'color'],
      ]],
      ['Blur', [
        ['horizontal melt', 'melt', 0, 2, 0.01],
        ['crest feather', 'feather', 0, 1, 0.01],
        ['glow halo', 'halo', 0, 0.5, 0.005],
        ['color softness', 'colorSoft', 0, 1, 0.01],
      ]],
      ['Motion', [
        ['speed', 'speed', 0, 3, 0.05],
        ['breathe', 'breathe', 0, 0.5, 0.01],
        ['shimmer', 'shimmer', 0, 1, 0.01],
        ['reveal on load', 'riseOn', 'check'],
        ['reveal time', 'riseTime', 0.2, 3, 0.05],
      ]],
      ['Cursor physics', [
        ['reach lift', 'cursorLift', 0, 0.6, 0.01],
        ['reach glow', 'cursorGlow', 0, 3, 0.05],
        ['reach radius', 'cursorRadius', 0.03, 0.8, 0.01],
        ['spring stiffness', 'stiffness', 5, 300, 1],
        ['spring damping', 'damping', 0.5, 30, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },
  web: {
    name: 'web',
    deps: {
      webDrag: c => c.webOn,
      webCount: c => c.webOn,
      webRadius: c => c.webOn,
      webIrregularity: c => c.webOn,
      linksPerNode: c => c.webOn,
      seed: c => c.webOn,
      nodeShape: c => c.webOn,
      nodeSize: c => c.webOn,
      nodeColor: c => c.webOn,
      lineWidth: c => c.webOn,
      lineOpacity: c => c.webOn,
      lineColor: c => c.webOn,
      perspective: c => c.webOn,
      depthFade: c => c.webOn,
      depthShrink: c => c.webOn,
      snapStiffness: c => c.webOn,
      snapDamping: c => c.webOn,
      webStiffness: c => c.webOn,
      autoSpin: c => c.webOn,
      autoTilt: c => c.webOn,
      dragSwing: c => c.webOn,
      swingDelay: c => c.webOn,
    },
    hint: 'drag a web node to pull it · drag empty space to rotate',
    openGroups: ['Web structure', 'Web nodes'],
    LAYOUT: [
      { t: 'background', groups: ['Background'] },
      { t: 'web', toggle: 'webOn', groups: ['Web structure', 'Web nodes', 'Web lines', 'Web depth', 'Web physics', 'Web motion'],
        rename: { 'Web structure': 'structure', 'Web nodes': 'nodes', 'Web lines': 'lines', 'Web depth': 'depth', 'Web physics': 'physics', 'Web motion': 'motion' } },
      { t: 'general', groups: ['Performance'] },
    ],
    bgKey: 'bg',
    DEFAULTS: {
      bg: '#ffffff', seed: 0,
      webOn: true, webDrag: false, webX: 0, webY: 0,
      webCount: 200, webRadius: 0.6, webIrregularity: 0.45, linksPerNode: 3,
      nodeShape: 0, nodeSize: 5, nodeColor: '#2a00ff',
      lineWidth: 1, lineOpacity: 0.65, lineColor: '#2a00ff',
      perspective: 2.2, depthFade: 0.75, depthShrink: 0.65,
      snapStiffness: 40, snapDamping: 6, webStiffness: 25,
      autoSpin: 0.15, autoTilt: 0, dragSwing: 1.2, swingDelay: 4,
      dprCap: 2, paused: false,
    },
    GROUPS: [
      ['Background', [
        ['background color', 'bg', 'color'],
      ]],
      ['Web structure', [
        ['web visible', 'webOn', 'check'],
        ['draggable position', 'webDrag', 'check'],
        ['node count', 'webCount', 20, 400, 1, 'rebuild'],
        ['seed', 'seed', 0, 999, 1, 'rebuild'],
        ['web radius', 'webRadius', 0.2, 1, 0.01, 'rebuild'],
        ['web irregularity', 'webIrregularity', 0, 1, 0.01, 'rebuild'],
        ['links per node', 'linksPerNode', 1, 6, 1, 'rebuild'],
      ]],
      ['Web nodes', [
        ['node shape', 'nodeShape', 'seg', ['●', '■', '◆', '○']],
        ['node size', 'nodeSize', 1, 16, 0.5],
        ['node color', 'nodeColor', 'color'],
      ]],
      ['Web lines', [
        ['line thickness', 'lineWidth', 0.2, 5, 0.1],
        ['line opacity', 'lineOpacity', 0.05, 1, 0.01],
        ['line color', 'lineColor', 'color'],
      ]],
      ['Web depth', [
        ['perspective', 'perspective', 1.2, 5, 0.05],
        ['depth fade', 'depthFade', 0, 0.95, 0.01],
        ['depth shrink', 'depthShrink', 0, 0.95, 0.01],
      ]],
      ['Web physics', [
        ['snap stiffness', 'snapStiffness', 2, 200, 1],
        ['snap damping', 'snapDamping', 0.5, 30, 0.25],
        ['web pull', 'webStiffness', 0, 120, 1],
      ]],
      ['Web motion', [
        ['auto spin', 'autoSpin', -1.5, 1.5, 0.01],
        ['auto tilt (y)', 'autoTilt', -1.5, 1.5, 0.01],
        ['drag swing', 'dragSwing', 0, 3, 0.05],
        ['swing response', 'swingDelay', 0.5, 20, 0.25],
      ]],
      ['Performance', [
        ['pixel ratio cap', 'dprCap', 0.5, 3, 0.25],
        ['pause', 'paused', 'check'],
      ]],
    ],
  },
};
